### ISSUE TITLE
Merge demo features to develop

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1011]
## Context/goal: 
Currently the new file uploader is part of demo-validation-requests; This branch has the functionality to upload files; This issue is about merging this file uploader with develop.

## Tasks

- [ ] Update branch with latest commits
- [ ] make branch for fund criteria config (sponsor dashboard)
- [ ] Form (steps to apply for fund)
- [ ] File uploader
- [ ] formula multiple records and validations 
- [ ] eligibility on frontend check
