### ISSUE TITLE
Epic. Signup-flow. Requester - Group of requests

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1027]
## Context/goal: 
- [x] Create new database tables
- [x] New API for fund requests (groups)
- [x] API for the admin panel (to process the requests, validations, etc)
- [x] API for the Me App
- [x] Logics for intermediate validations to regular validations

________

In order to fulfill the goal of the milestone, we have to group the requests sent to the validation dashboard.

This should be implemented in couple of steps:

### Intermediate validations #1025
Implement intermediate validations before the full group is validated. 
A group can be composed of 1 or more validation requests (record level). Do not mark the complete validation group as validated - until all record validation requests have passed the validation. 

- [x] Not necessary all to have "Validated" status. If all passed the validation, but 1 had been rejected - full group is rejected. #1025
- [x] When all requests from the group are approved or rejected - we send an email notification with the status of the Group to the requester. #1037

### Assign the group to a validator #1026
- [x] When a validator starts to validate a group of records - marks it as "In progress" #1026
- [x] When displaying the list of validation groups - show if it is in progress. If it is "In progress" - show who did start working on it. #1026
