### ISSUE TITLE
Epic. Signup-flow. Requester - Record level validations (statuses and actions)

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1030]
## Context/goal: 
On the record level (within a group) - now we have 3 statuses and actions: Pending, Accept (accepted) and Reject (rejected). 

- [x] In the case of reject - It will show a modal to inform that it will reject the full group, and if you are sure about it. (NEEDS design)
- [x] When rejecting - also provide (optionally) a clarification why it was rejected (it will be sent to the client)
- [x] Add additional action - "Ask". It will open a modal with a Textarea field - with some explanation to send to the requester. (NEEDS design)
