### ISSUE TITLE
Epic. Signup-flow. Requester - Application form workflow

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1033]
## Context/goal: 

- [x] Based on the criterias of the fund the form will be created. #1034 
- [x] The form will be strictly connected with the fund
- [ ] In the form users will need to login with DigiD (will simulate for now) #1035 
- [x] The form will create records to the user, based on the criteria. It will ask the user values for each criteria record. 
- [x] It will create a group of records and send them to the validation dashboard of the Organisation of the Fund. 

### DigiD part - working with pre-validations
- [ ] In most cases - we will have a prevalidated list of BSN numbers. After the requester logged in via DigiD - we validate his BSN number and check it with the prevalidated list. If not found in the prevalidated list - send him to fill in the complete application form.

**Comment by danrminds** [comment]
@jamalv @maxvisser Should the user login first with Me? Or should he create a Me Identity first? 
Should we use as a first step the similar workflow of the Demo Provider signup form?

**Comment by jamalv** [comment]
Yes, the user needs to create an identity or log in in the first step.

If they fill an email adres which has not been used yet, we can create the account in the background and log the user in. We don't need their name and other details.
* Initially we also don't need to validate the email address by clicking a link, later this might be a good idea.

If they fill an email address which has been used already, we can send a login url to their mailbox and ask them to click the link in the signup form.

**Comment by jamalv** [comment]
Hopefully the video's in #development (chat channel) also clarify this further.
