### ISSUE TITLE
Epic. Signup-flow. Requester - Wireframes Webshop Fund page

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1041]
## Context/goal: 
Right now - we need a few more wireframes for the Fund page of the webshop. We need them for the following usecases:

#### 1. You open the fund, and you did not apply yet
- [x] In this case we need to show a page with the Fund information, criterias, and a possibility (button) to apply for it.
- [x] A message that if he wants to check the fund application status (if already applied) - he should login with Me. Maybe a button for it as well. 
#### 2. You opened the fund but you already applied for it
- [x] Status information (applied and not processed yet, in progress, needs more information from him, rejected).

**Comment by jamalv** [comment]
Allright, this one got a bit out of hand :) I made a video to explain the mockup and concepts behind it: https://drive.google.com/a/forus.io/file/d/1r8wgM5fzQ24V-cOUyY7DD7_WkQvbTVac/view?usp=sharing

The figma prototype can be accessed here: https://www.figma.com/proto/vHUKdbZ7pR4q07g7NRrQ75/Webshop---Prototype?node-id=172%3A6979&viewport=131%2C153%2C0.058287493884563446&scaling=scale-down-width

The figma project here: https://www.figma.com/file/vHUKdbZ7pR4q07g7NRrQ75/Webshop-Prototype?node-id=172%3A5167

**Comment by danrminds** [comment]
Hi @jamalv 

Perfect, I have everything I need for our current scope. 

Some remarks about the out-of-scope things:

1. You should the map with providers / products, etc - but we already have a new one (almost finished). If we need to refine - we need to refine that one. 
2. About deletion of records - yes, we need that. But we have to think all the usecases - what happens after you delete it (with pending validation requests, with accepted validations requests but not vouchers yet, with received vouchers based on these records and so on).

**Comment by jamalv** [comment]
Awesome, max is working on adding the maps to the prototype so we can refine them there :D

**Comment by jamalv** [comment]
2. Yea, probably there are many edge cases to consider, we can slowly extend the prototype to include those kind of things. 

Off topic: Lena will be joining us at the office this week by the way :) So if you're in Groningen you're of course welcome as well!
