### ISSUE TITLE
Epic. Signup-flow. Requester. OVERVIEW

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1045]
## Main asssignee: @danrminds 

Will update this task based on the progress that is made

### @myshelova
- [x] Update the Records screen of the Me App (Android and iOS)
- [x] Make the new screen with modal after you scan a validation QR code
- [x] Final version of the Application form
- [x] Updated version of the Provider signup form #1036 
- [ ] Fonds page on the webshops. 

### @sashooa 
- [x] View of the list of requests groups #1042 
- [x] Ask for additional proofs #1029 
- [x] Reject a record validation #1028 

### @danieltcacenco 
- [x] Return back on the dev environment the discussed parts of the "Records" functionality
- [x] Implement the new API calls / routes that Valentin will prepare here #1043

### @dev-rminds 

Application form workflow #1033
- [ ] DigiD simulation. #1035
- [x] Sponsor actions / creation of the form based on fund criterias #1034
- [x] Work with pre-validations #1044
- [x] Align the workflow of the form #1033 

Validation requests in groups / validation dashboard (fund application groups)

- [x] Groups are assigned to an organisation
- [x] Intermediate validations #1025
- [x] Validators view all the requested groups to the organisation they are now in #1026 
- [x] Validator assigns himself to a group (starts processing) #1027 
- [x] Statuses of the Group #1026
_- when in progress - #1031_
_- send email notification - #1037_
- [x] Record level statuses and actions #1030
_- Ask for more information (modal action)_
_- Reject a record validation (modal action)_
- [x] Switch between organisations #1024 
- [x] Update front-ends #1057
