### ISSUE TITLE
Epic. Signup-flow. Requester - New e-mail notifications

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1068]
## Context/goal: 
Send email notifications when:

- [x] A person applied for a fund - with a confirmation and "please wait for your validation requests to pass"
- [x] The fund request was "accepted", "rejected", "partly accepted"
- [x] 1 fund request record was rejected (with optional "message")
- [ ] Additional request for extra proof. With a link to fill in the question the extra info is asked for.
