### ISSUE TITLE
Epic. Sprint 2. Create product vouchers. Check activationcode.

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1078]
## Context/goal: 
When creating a product voucher - we'll have 2 options to create one:
 - Gift 
 - using an activation code

### If gift - 
no regulations applied

### If via activation code - 
- [ ] show a modal to fill in the activation code. 
- [ ] check if activation code is used already or not
- [ ] show modal with reject if already used
- [ ] if not used - cancel / delete the activation code
- [ ] create the product voucher

**Comment by danrminds** [comment]
https://drive.google.com/a/rminds.nl/file/d/1JZvSAynFGZHO11uo0qvELBA27X6FT3FN/view?usp=sharing
