### ISSUE TITLE
Epic: Filters, search and export for tables 

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#108]
Implement the filtering feature in the tables of the dashboard

transaction overview on sponsor/provider dashboard
- [ ] export transactions https://github.com/teamforus/forus/issues/359
- [ ] filter transactions https://github.com/teamforus/forus/issues/635
- [ ] search transactions https://github.com/teamforus/forus/issues/636
add these options aswell on financial dashboard of sponsor:
- [ ] filter search financial dashboard https://github.com/teamforus/forus/issues/306
- [ ] sponsor filter provider applications https://github.com/teamforus/forus/issues/635
- [ ] export providers on sponsor dashboard https://github.com/teamforus/forus/issues/731

Design:
https://www.dropbox.com/s/dkcjj4qo212ne5j/Filter%2C%20search%2C%20pagination.tif?dl=0

**Comment by maxvisser** [comment]
For me currently this has really low priority but could you explain abit more what you meant with this?
