### ISSUE TITLE
Epic. Sprint 2. Create product vouchers. Design

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#1080]
## Context/goal: 
Create the designs for the sponsor for creating product vouchers.
Still to discuss with @dev-rminds 

- [x] Product vouchers table
- [x] Select "Gift" or "via Activation code"
- [x] Bulk creation of vouchers
- [x] Code already used / Product voucher created

**Comment by danrminds** [comment]
https://drive.google.com/a/rminds.nl/file/d/1JZvSAynFGZHO11uo0qvELBA27X6FT3FN/view?usp=sharing
