### ISSUE TITLE
Release: v0.5

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1122]
Please branch from v0.4

# To be added to: https://github.com/teamforus/forus-frontend/pull/737

## Bug
- [x] Sponsor dashboard: aproving providers: filters based on funds don't work https://github.com/teamforus/forus/issues/1154
- [x] Fix multiple fund title: https://github.com/teamforus/forus/issues/1128

## Must have
- [x] Login without organisation: hide on all dashboards (when choosing organisation) https://github.com/teamforus/forus/issues/1129
- [x] Update title on sponsor dashboard "aanbieders" page to: Aanbieders voor [fund-name] https://github.com/teamforus/forus/issues/1130
- [x] Update financial dashboard: totaal gestort budget https://github.com/teamforus/forus/issues/1131
- [ ] Switch map and offers on budget voucher page: https://github.com/teamforus/forus/issues/1132

## Should have
- [x] On all generic dashboards: Hide our logo on the top left: https://github.com/teamforus/forus/issues/1133
- [x] Sponsor and validator: Replace "gemeente" with "sponsor" or "validator" (top right) https://github.com/teamforus/forus/issues/1134
- [x] Activate all funds automatically after filling activation code : https://github.com/teamforus/forus/issues/1135

## Nice to have
- [ ]  Add home page components to home menu on webshop (scroll within page)
  - [ ]  Fondsen
  - [ ]  Aanbiedingen 
  - [ ]  Kaart
  - [ ]  Uitleg
  - [ ]  Vragen
- [ ]  Show email adres on model
- [ ] Context switcher (can be mvp) https://github.com/teamforus/forus/issues/674

## Done:
- [x] https://github.com/teamforus/forus/issues/1116
- [x] https://github.com/teamforus/forus/issues/1120
- [x] https://github.com/teamforus/forus/issues/1121
- [x] https://github.com/teamforus/forus/issues/1123

**Comment by jamalv** [comment]
Dan, could these issues be implemented asap? :)

**Comment by jamalv** [comment]
Some more work to be done, will work on translating these tasks to concrete issues now.

**Comment by maxvisser** [comment]
clarified bug 1 https://github.com/teamforus/forus/issues/1154

**Comment by maxvisser** [comment]
will close this issue as v0.5.0 is relead; I think for the nice to haves there are already new issues
