### ISSUE TITLE
Fund selector is not really usable with multiple funds more than 5

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1172]
## Context/goal: 
The UX of the fund selector on sponsor dashboard is bad UX with multiple funds

Open financial dashboard -> fund selector
Open voucher generator -> fund selector
Open provider approval - > fund selector

Each time a page is clicked sponsor needs to select a fund. I would change this to opening the page with all information or a fund automatically selected and make the fund a filter. instead of such big selectors.

## Task
- [ ] save fund state on first fund selection
   - keep this fund selected while changing between financial dashboard, voucher generator and provider approval until user selects a different fund.
- [ ] remove 'Select different fund' button
- [ ] list all funds instead
- [ ] make fund selectors much smaller maybe 20% width (around 150px width)\

example of how fund selectors will look:
![image](https://user-images.githubusercontent.com/10818702/76887052-f2b15800-6881-11ea-9a42-0eb573732a41.png)

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/69165595-1cd05480-0af2-11ea-9ec1-28a434d1a023.png)

**Comment by maxvisser** [comment]
I think you got the issue wrong @danrminds its not really a bug. But a UX problem.
Open financial dashboard -> fund selector
Open voucher generator -> fund selector
Open provider approval - > fund selector

Each time a page is clicked sponsor needs to select a fund. I would change this to opening the page with all information or a fund automatically selected and make the fund a filter. instead of such big selectors.

**Comment by maxvisser** [comment]
proposal
- make fund selectors smaller
- make them always visible
- make them a different color when selector

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/76886976-d7464d00-6881-11ea-909b-c845c1965a3d.png)
