### ISSUE TITLE
Epic: Webshop update

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#1175]
## Design
We will make all designs in Figma, and into a prototype. @jamalv will put a checkmark if a component is done, approved by stakeholders, and ready to be developed and brought to production. 

- [ ] Funds page & Vouchers page @Myshelova https://github.com/teamforus/forus/issues/1071
  - [ ] Add and review texts @linda-90 
- [ ] Styleguide / Components @Myshelova 
- [ ] Offers page (full page products overview) @Myshelova https://github.com/teamforus/forus/issues/1048
  - [ ] Add and review texts @linda-90 
- [ ] Providers page (full page map and list) @Myshelova https://github.com/teamforus/forus/issues/1048
  - [ ] Add and review texts @linda-90 
- [ ] Records page @Myshelova 
  - [ ] Add and review texts @linda-90 
- [ ] Home page 
  - [ ] Add and review texts @linda-90 
- [ ] Home page when logged in (new page) @maxvisser, maybe we can create some wireframes?
  - [ ] Add and review texts @linda-90 
- [ ] Link pages and create prototype
- [ ] Add (missing) modals and texts to prototype

## Implement
The implementation of the designs will be in smaller iterations. @maxvisser will guide the developers in how he would like the development proces to be.

- [ ] Issues to be added by max when design components are done.

**Comment by maxvisser** [comment]
imo all UI changes should also be done on old design first if you want to gradually implement it.

**Comment by jamalv** [comment]
I would like to leave that choice up to you. As long as we end up with the (approved by stakeholders) designs, the best path to get our products there, is up to you :)

**Comment by danrminds** [comment]
I think we should implement it gradually. We now have a new menu, as well as almost finished vouchers / funds page - which is important for the release of the features we already worked on, like the application form.

We should prepare this for implementation, and update other pages on the go.

**Comment by maxvisser** [comment]
Yes to gradually implement and keep a common design language is the difficulty I see. What do you think @danrminds as the plans are now like a complete overhaul. I currently don't see a easy way to do it gradually without first implementing a redesign on current UI or implementing all UI changes in old design.

**Comment by maxvisser** [comment]
I would propose for Lena to take Alex his designs and port the prototype over to the current design language. We will gradually implement the new UI changes and after this we will do the redesign with angular upgrade

**Comment by jamalv** [comment]
Plan for this issue:
* Re-create a current webshop in figma
* Create the common webshop
* Start itterating 

Closing this issue in favour of: https://github.com/teamforus/development/issues/270
