### ISSUE TITLE
Invite current providers: Sent an e-mail to existing provider that a new fund is about to start

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1192]
## Context/goal: 
On forus-backend we have mail called fund applicable. This mail is sent when the start date is reached. Providers selected to get this mail were providers that had a specific fund_category. As we removed fund categories this email was disconnected. 

## Who are applicable providers
We don't know which providers are applicable for a newly created fund but we do know this for funds that are renewed. This issue is about sending an fund applicable mail with a button to easily apply for the fund to providers that were approved for a different fund from a sponsor.

### Prerequites
- Provider applied for fund_id 1 in 2018 
- Sponsor created a new fund, fund_id 2

## Userflow Sponsor
-  User logins in sponsor dashboard
- User sees newly created fund that is configured and is now in state 'paused'
- User goes to /organizations/{sponsor_org_id}/providers
- User clicks on fund_id 1
- User clicks invite providers button
- Modal opens where user select fund_id 2; sees preview of e-mail that is sent to providers.
- presses sent and email is sent to all organization owners

## Userflow Provider
- Provider gets a invitation mail for a new fund from a sponsor he already applied for once.
- Provider clicks a magic blue button 'directly apply'
- Provider goes to provider dashboard of fund_id 2 its implementation.
- Provider accepts invitation by accepting invitation token. User will get a option to login to dashboard of implementation of fund invitation
- IN database we have in fund_providers state 'invited'; As user pressed button in mail he is now accepted and gets a SUCCESS! you are ready to serve customers for this fund! popup

this is mvp.

## Tasks
- [x] text for landing page invitation ( cta: update products, organisation details etc )
- [x] text for e-mail
- [x] design for landing page invitation
- [x] create markup for landing page
- [x] implement backend functionality invitation token to accept invitations

Nice to have:
- fund_provider_invitation table for the sponsor to select multiple funds he want to invite the provider list for.
- being able to only select certain provider to invite.
- See status of each invitation
- Resend invitation
- Undo invitation request
- provider can have a setting to auto accept each invitation he gets. ( we need an activity monitor for this to see when provider was last active on our system)

**Comment by maxvisser** [comment]
https://github.com/teamforus/forus/issues/1166 also a support problem

**Comment by jamalv** [comment]
I would like to add a nice-to-have (should probably keep it as a seperate issue: https://github.com/teamforus/forus/issues/978) 

It would be nice to have: to be able to bulk invite providers with a csv file with email adresses.
- requires a invitation email with instructions on how to sign up for the fund and some context
