### ISSUE TITLE
Providers should select a business type on login if they don't have one.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1203]
## Main asssignee: @

started from branch: release-v0.6.0

## Context/goal: 

 Userflows:
 When a provider logins in on a provider dashboard and his organisation does not have a business type. They should get prompted to select one 

## Tasks
- [ ] write text for popup modal
- [ ] make preview of how modal should look.
- [ ] implement modal and show it when organization does not have any business type selected.

**Comment by jamalv** [comment]
Lets keep it simple: 

![image](https://user-images.githubusercontent.com/30194799/71325109-54af2b00-24e8-11ea-9357-64b569d3a7a7.png)


Kies een categorie voor uw organisatie

Door een categorie toe te voegen bent u makkelijker te vinden

**Comment by jamalv** [comment]
Maybe disable closing the modal; please check if there is already "other" if we want this. otherwise a shopkeeper will be stuck
