### ISSUE TITLE
Optimization: cache approved provider list, product sample

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1211]
## Context/goal: 
When a fund 1 month active, alot of the provider for the year are signed up and in the system. The provider list is getting after this moment pretty static. For frontends to load more quickly we could make a seperate route which has a cached approved provider list per fund. 

We should only really query the database when doing transaction (authenticate to do a transaction) or when buying a product voucher in webshop. When these list are more static resources the map can load much quicker.

## task

- [ ] make a route which has a cached list of providers 
- [ ] make a route which has a cached list of products sample
- [ ] refresh each cached route each 12 hours

**Comment by jamalv** [comment]
Can we update the frequency? I think even if we update the cache every 5 minutes, we will have mostly the same advantages? A provider will want to check if he appears on the webshop :) What is the minimal amount of time? If it could be 1 minute I would even do that :)

**Comment by maxvisser** [comment]
Discussed this during last sprint planning. This is not desired by the team so I will close the issue
