### ISSUE TITLE
DigiD unhappy flows

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1235]
## Context/goal: 
This issue is about checking each unhappyflow;

- [ ] filling in the wrong password in on DigiD. (authentication process failed)
- [ ] an another identity already claimed BSN number 
- [ ] text for error messages etc

## Task
- refine all unhappy flows
