### ISSUE TITLE
create seperate compontent for Nijmegen requester signupflow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1269]
## Main asssignee: @

Figma prototype: https://www.figma.com/proto/buNhwrhiuG23hrxWZRGkrC/Nijmegen?node-id=47%3A618&viewport=158%2C344%2C0.20095285773277283&scaling=min-zoom

Figma pages: https://www.figma.com/file/buNhwrhiuG23hrxWZRGkrC/Nijmegen?node-id=47%3A22

deadline: this friday (normally next friday but this needs to be tested and released sooner)

## Prerequisites:
- fund list page will be off; (for testing turn it off in backend config)
- start button should go to first fund request of implementation 

## Context

Userflow
1. user goes to nijmegen webshop (digid is enabled on this implementation
2. on home.pug clicks on start
3. user logges in and is returned to /#!/fund/{fund_id}/request
4. User loges in with DigiD
5. User is returned to  /#!/fund/{fund_id}/request after succesfull DigiD auth
6. User sets a checkbox on meedoen_2020_eligible record.
7. record gets automatically validated by the validator that is assigned to fund #1287 #1251 
8. User gets voucher

## Tasks
- [ ] hide Me app block when logged out (no need for people to login with Me-app)
- [ ] hide criteria on overview page (when logged out) -> Criteria will only be shown on step of checkbox
  - [ ] overview page should also hide criteria
- [ ] remove description "sign_up-pane-text" (hide description below sign in with e-mail -> less text is better
- [ ] when logged in you should not be able to go to next step without login with digid -> DigiD is a requirement to send anything to validator dashboard
- [ ] meedoen_2020_eligible should be a checkbox page 

## Example of stepper
![image](https://user-images.githubusercontent.com/10818702/70618064-3ad13680-1c12-11ea-950f-5e12e4714eb6.png)

## Adjust implementation styles for Nijmegen for signupflow for providers

- [ ] adjust bar color of sign_up-steps to implementation primary color (this bar has round edges)

**Comment by jamalv** [comment]
Welkom op de website van Meedoen-regeling. U kan hier uw tegoed aanvragen, het aanbod zien en het geld dat u kunt besteden.

Voldoet u aan de voorwaarden van de meedoen regeling?

START AANVRAAG

Controleer of u voldoet aan de voorwaarden van de meedoen regeling.

Klik op de start knop om uw aanvraag te starten. Gebruik uw eigen e-mailadres.

**Comment by jamalv** [comment]
styling: https://github.com/teamforus/forus/issues/1242

**Comment by maxvisser** [comment]
https://github.com/teamforus/development/issues/191 reference
