### ISSUE TITLE
Implement better errors and show time left on activating voucher code modal

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1342]
## Context
The activation code modal is a modal where a user can fill in a prevalidation token to apply for a fund. Still alot of people are getting a terrible experience with this modal and the workflow. Let's fix it. Giving back better errors and limiting fast attempts.

## Goal
User should not be able to attempt multiple tries right in sequence of each other.

After first attempt we should tell the user to wait 2 minutes and show a timer or show the time left in error message.

## Task

- [ ] limit attempts on frontend to make user feel he has a small amount of attempts
- [ ] Show the amount of attempts user used. 
- [ ] Show time left to make new attempt

## alternative
 Maybe even let the user fill in the code again on second try. (easy fix but maybe bad UX)

**Comment by GerbenBosschieter** [comment]
Reopend this issue. Current situation is even worse than before and it doesn't even come close to whats is purposed in the issue.

## Problems:
- User gets a error message after one try, this was after three times.
- It doesn't look like the timer is resetting after one minute. I waited for one minut and tried it again, immediately was after second try.
- error message is really bad, to much text and doesn't  inform the user correctly.
- It causing a lot of support calls that I can't solve.
- I would like to see this change ASAP. This is the first experience with the system for the users and it's a bad one.

## MVP Solution
- Change it back to how it was. That was much better.

## Long term solution
- [ ] Implement the error message after three times and not 1
- [ ] Better text

## Example DigiD
See image blow. This is a error message you get after three bad login attempts.
**Translation (google translated):**

You have entered incorrect information 3 times since January 24, 2020 at 10:50 AM (Dutch time). For security reasons, you cannot use your password and / or SMS until 11:06 AM (Dutch time). You can try again in 13 minutes.

<img width="447" alt="Screen Shot 2020-01-24 at 10 51 17" src="https://user-images.githubusercontent.com/38419514/73060185-97717380-3e97-11ea-95cc-0929b6747533.png">

**Comment by maxvisser** [comment]
tested the revert; but it does not solve the problem of having only one attempt; also after the attempt user does not get any feedback trying again
