### ISSUE TITLE
Make printables on voucher generator implementation specific

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1424]
## Context/goal: 
Some sponsor use voucher generator on general sponsor dashboard; The link and logo are wrong on the printables (these are forus.io and our logo in right top corner)

## Task
- [x] fetch implementation key of selected fund
- [ ] get notice based on this implementation key
- [x] use link of implementation on general sponsor dashboard
- [ ] if available use implementation logo on general sponsor dashboard
