### ISSUE TITLE
Implementation dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1531]
### Context
User will go to implementationname.forus.io/admin and login with identity; An implementation needs an organization owner. For example organization id 1; which can assign the role manage_implementation to an employee. These employees can access this dashboard.

The dashboard will contain the implementation name and fund attached to the implementation (active or pending)

We will add:
- option to add description
- option to add info link
 
## Task
- [x] Add new angular app for implementation dashboard
- [x] Implementation has an owner organization
- [x] Implement new permission/role manage_implementation which can access this dashboard.
- [x] implement new pages:
	- implement edit page
- [x] implement on webshop
  - name
  - description
  - new menu item
	- Link to new page
	- or info url 
	- change css break for mobile to 1280 instead of 1024 ( to allow for more menu items)

## Additional info
Figma:
https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW/CMS?node-id=1654%3A68682

### First itteration
[View the explainer video](https://drive.google.com/a/forus.io/file/d/1QHlK88VMi9mkk4AygRArdCQEPW9aIceD/view?usp=sharing) | [ View the figma prototype](https://www.figma.com/file/N3p59HvuJoKr7RgT5AYAVW/CMS?node-id=1731%3A67856)

**Comment by maxvisser** [comment]
needs designer review @danrminds

**Comment by danrminds** [comment]
@maxvisser Can we close this one?

**Comment by maxvisser** [comment]
yes
