### ISSUE TITLE
Sign-up v2: Change closed and open states around

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#1590]
Checkmarking the checkbox can be confusing.
Adding checkmark will give you the option to add bussiness hours. But if there are no bussines hours it feels like you can checkmark to teel the users the shops is closed that day.

**URL tested:** https://dev.forus.io/provider/#!/sign-up-v2

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1904x1000 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6acdd9ec34bbdf0875126916a39d9bda9aab80ff/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/6acdd9ec34bbdf0875126916a39d9bda9aab80ff/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdev.forus.io%2Fprovider%2F%23!%2Fsign-up-v2&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dev.forus.io/provider/#!/sign-up-v2&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack** 

## Task
- [ ] Switch around closed and open states for the checkboxes
- [ ] Replace text above them to "Gesloten"
- [ ] check the first checkbox automatically 'all weeks days are the same';

![Screenshot 2020-06-22 at 19 01 30](https://user-images.githubusercontent.com/33207036/85315203-e2c99580-b4ba-11ea-84a8-66325c2290ad.png)

**Comment by maxvisser** [comment]
Switch around closed and open states for the checkboxes

Another solution would be to check the first checkbox automatically 'all weeks days are the same'; so open some inputs already to indicate what the checkmark means.

**Comment by maxvisser** [comment]
discussed this issue and we think that the concept of closed and open is just werid. so a text change is not enough; 

We discussed two things we want to change:
1. now when you create a new location, the location is closed on all days by default. We now want to show the opening hours fields as standard during the weekdays (Monday to Friday). 
2. We thought it was weird that you need to check a checkbox to indicate that you are open on that day. We would like to see it the other way around, you check something to indicate that you are closed that day

**Comment by GerbenBosschieter** [comment]
@maxvisser even better

**Comment by danrminds** [comment]
@aghimpu 

Reverse the use of checkboxes. Checked = closed. Replace text above them. 
Example:
![Screenshot 2020-06-22 at 19 01 30](https://user-images.githubusercontent.com/33207036/85315203-e2c99580-b4ba-11ea-84a8-66325c2290ad.png)
