### ISSUE TITLE
Make text adjustments on Signupflow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1624]
## Context/goal: 
Change text on signupflow which were changed yesterday part of text review done by @maartenfv @linda-90 

## Task
- [ ] Look through pages in figma
- [ ] look through current signupflow-v2
- [ ] spot differences and adjust each step of signupflow with new texts.
