### ISSUE TITLE
Bulk upload optimizing speed

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1652]
## Tasks

- [ ] Checking existing emails could be faster

- [ ] Check product_id available could be faster (which ones are out of stock? how many per product)

- [ ] Uploading prevalidation CSV (not sure if it can be faster)
