### ISSUE TITLE
Prevalidations hashing of bsn numbers

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1726]
@maxvisser commented on [Mon Jul 06 2020](https://github.com/teamforus/general/issues/263)

Learn more about improvement proposals: https://bit.ly/2xLJT3R

## Impacted areas:

- [ ] Design
- [ ] Code
- [ ] Infrastructure
- [ ] Users
- [ ] Finances
- [ ] Processes

## Current situation
A validator can upload prevalidations in bulk. A requester can redeem a prevalidation with an activation code or using a valid BSN number from DigiD. 

## Desired situation
Citizen service numbers are sensitive personal data (classification of the BIV principle: essential, absolute and secret), so this must be treated with the utmost care. The municipality and Forus therefore want to minimize the use of BSN's (social security numbers). To prepare residents, Forus therefore proposes to hash the BSNs. This ensures that the thousands of BSNs are not visible in the list.

## Plan
The proposal is to upload a BSN cryptographic fingerprint instead of the citizen service number itself. Forus can then compare the BSN obtained by DigiD (with the user's approval) with this fingerprint obtained by the Oracle Database which contains all bsn numbers which a are eligible for the fund.

<details>
<summary>comments</summary>

---

@maxvisser commented on [Wed Jul 22 2020](https://github.com/teamforus/general/issues/263#issuecomment-662394430)

Optional encryption
BSN, UID

_bsn,_uid -> a underscore show that column of this header is encrypted

Master key Forus

Fund keys -> share key with municipality

reencrypt with master key

electron app where they can fill in fund key to encrypt CSV

What is the UX?

Do we need decrypt at any point the BSN-numbers in CSV

---

@jamalv commented on [Thu Jul 23 2020](https://github.com/teamforus/general/issues/263#issuecomment-662985062)

Next step: write down conclusions of research. Share this with stakeholder to make a final plan.

---

@jamalv commented on [Thu Jul 23 2020](https://github.com/teamforus/general/issues/263#issuecomment-662985166)

@maxvisser could you help @dev-rminds with this?

---

@maxvisser commented on [Wed Jul 29 2020](https://github.com/teamforus/general/issues/263#issuecomment-665600235)

what kind of algroritm? -> SHA256

---

@maxvisser commented on [Mon Aug 03 2020](https://github.com/teamforus/general/issues/263#issuecomment-668199025)

an example BSN '100009756' and an example key 'MaxVisser' should result in '2E8CD5F95F4A6FECAB339580BB2C6CFC93E580E9A29B592EC27D9E916CE79776'

---

@maxvisser commented on [Thu Aug 06 2020](https://github.com/teamforus/general/issues/263#issuecomment-669755343)

Valentins proposal is to make a working prototype. We need this to answer any question we get about this from Groningen.

---

@maxvisser commented on [Tue Aug 11 2020](https://github.com/teamforus/general/issues/263#issuecomment-671975586)

```sql
create or replace function gn_sp_hash (

  p_sofi_nummer number)

return varchar2

as

  l_return varchar2 (64);

  l_key    varchar2 (9);

begin

  l_key := 'MaxVisser';  -- later uit configuratietabel

  select dbms_crypto.mac(utl_i18n.string_to_raw(lpad(p_sofi_nummer, 9, '0'), 'al32utf8'), 3, utl_i18n.string_to_raw(l_key, 'al32utf8'))

  into   l_return

  from   dual;

  return l_return;

end;

```

---

@maxvisser commented on [Tue Aug 11 2020](https://github.com/teamforus/general/issues/263#issuecomment-671975809)

@dev-rminds code snippet 

---

@maxvisser commented on [Tue Sep 01 2020](https://github.com/teamforus/general/issues/263#issuecomment-684805453)

@jamalv could we talk about this one ?

---

@maxvisser commented on [Tue Sep 01 2020](https://github.com/teamforus/general/issues/263#issuecomment-684809156)

Hashing vs encryption

---

@maxvisser commented on [Tue Sep 01 2020](https://github.com/teamforus/general/issues/263#issuecomment-684809706)

how to display information? and where it is needed?

---

@jamalv commented on [Tue Sep 01 2020](https://github.com/teamforus/general/issues/263#issuecomment-684813716)

@maxvisser sure, so this is what we've shared with the client so far: https://www.figma.com/file/rW80bGvSS7TKXovctNjjUQ/Relations?node-id=1%3A2164

I think maybe displaying it is not needed? If the validator also uploads a customer identifier? What would you like to discuss here? Should we have a call?

---

@jamalv commented on [Wed Sep 02 2020](https://github.com/teamforus/general/issues/263#issuecomment-685463773)

We had a call yesterday and discussed that max will communicate directly with the client what is the best path; 

my preference goes towards speed of implementation (less complexity is better) and I think it might be goo to add custom user identifiers to the file instead of encrypting / decrypting the BSN's, but I'll go with what max and the client think is best :)
</details>

## Task

- [ ] Check MYSQL function of oracle database
- [ ] propose new MYSQL function for hashing or create a script which hashes the BSN
- [ ] Add to prevalidation a way to upload _bsn and _partnerbsn which are hashed. Values can be hidden on table
