### ISSUE TITLE
NOP Webshop: Check FAQ for changes

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1739]
@maxvisser commented on [Tue Sep 08 2020](https://github.com/teamforus/general/issues/416)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Dead link in FAQ
![image](https://user-images.githubusercontent.com/10818702/92446641-66d81300-f1b6-11ea-8fda-17d6062b8aa7.png)

## Task
- [ ] change dead link to working one  https://www.noordoostpolder.nl/meedoenpakket
- [ ] add ```<a href>``` for links
- [ ] check FAQ for changes
[figma.com/file/pUWeZwelwsJK8W58ZGip9r/Webshop%3A-Noordoostpolder?node-id=658%3A88&viewport=-270%2C685%2C0.36613044142723083](url)
