### ISSUE TITLE
Standardize login success modals: e-mail confirm text

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1743]
@maxvisser commented on [Wed Jun 03 2020](https://github.com/teamforus/general/issues/224)

## Current situation
We have in the Me-app, on the dashboard and webshop alot of different kind of login success messages. Some have had text review, design review but others didn't. I would like to align them all with the most ideal text and design choices.

An example:
![image](https://user-images.githubusercontent.com/10818702/83602329-a74e4200-a572-11ea-8f95-407c8a0410fb.png)

## Desired situation
This IP about creating one standardized login success message which is the same for all products.

Example of desired situation:
![image](https://user-images.githubusercontent.com/10818702/83602405-c6e56a80-a572-11ea-910b-245625cb1d3d.png)

## Plan
https://www.figma.com/file/zHYkRxuahVLodzMtzGP2Uj/Login-success-modal?node-id=2%3A4

## Task
- [ ] check website modal auth for texts
- [ ] add svg and styling/svg for dashboard and new consistent texts.
- [ ] add svg and styling/svg for webshop and new consistent texts.

**Comment by maxvisser** [comment]
@SjoerdHilhorst Please check the website, dashboard and webshop for all auth success messages; Add SVG and new consistent texts.

**Comment by SjoerdHilhorst** [comment]
is the desired situation already implemented somewhere?

**Comment by maxvisser** [comment]
I am not sure.
