### ISSUE TITLE
Webshops fund request: Already requested this fund

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1748]
## Context/goal: 
![image](https://user-images.githubusercontent.com/10818702/92569546-0f52a980-f281-11ea-8e6c-ed2784d4983f.png)

## Task
- [ ] Title_fund_request_applied is "Aanvraag in behandeling"
- [ ] fund_already_applied is "Er is al een aanvraag in behandeling"
- [ ] replace criteria's with criteria title
   - example: 'bijstandsnorm' moet 120% zijn becomes the criteria title
