### ISSUE TITLE
Make Fund request auto validation flow generic

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1752]
@maxvisser commented on [Wed Sep 09 2020](https://github.com/teamforus/general/issues/434)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description

There is another fund which wants to utilize the auto validation flow. (same sponsor)

This flow currently has alot of hardcoded content.

As you can see in this file:
https://github.com/teamforus/forus-frontend/blob/328ea303b10683c4c5b1b5c74b42711b1e7ebe48/src/sources/forus-webshop/pug/tpl/pages/fund-request-auto.pug

## Tasks
- [ ] research abit to see if flows can be merged (auto validation and normal flow)
- [ ] make tables possible in markdown
- [ ] move checkmark below description

**Comment by maxvisser** [comment]
Needs brainstorm session next week

**Comment by maxvisser** [comment]
we want to do refactoring first before merging the two.
