### ISSUE TITLE
Webshop potjeswijzer: Change header photo

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1762]
CR: https://github.com/teamforus/general/issues/372
## Task
- [ ] change header photo to:

<img width="1920" alt="Image" src="https://user-images.githubusercontent.com/10818702/93074983-714a4f00-f685-11ea-9d36-2aa3a4412fe7.png">

- [ ] move text to left
- [ ] make color of text black.
- [ ] decrease header-description width

<details>
<summary>Desired result</summary>

![image](https://user-images.githubusercontent.com/10818702/93075303-e453c580-f685-11ea-98ed-a8d8820f0701.png)

</details>

**Comment by GerbenBosschieter** [comment]
@maxvisser Has anybody thought about the fact that the text is not readable if you the screen gets smaller?

**Comment by maxvisser** [comment]
I only looked on the smalest resolution. My first instinct thought it was a bad image. After checking it seemed fine. Now after some screenshot of you; Image needs to be changed alot. I would prefer to only start changing / designing images after stakeholder approval 

@jamalv  I will put this one on hold for now.
