### ISSUE TITLE
Adding landmarks "role" tags to regions of code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1774]
![image](https://user-images.githubusercontent.com/10818702/93762448-debf2800-fc0f-11ea-9c83-55b155ea94ee.png)

## Resources
https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/ARIA11

## Task
- [ ] add to block-navbar: role="navigation"
- [ ] add to section-header: role="banner"
- [ ] add to page-home: role="main"
- [ ] add to footer: role="contentinfo"

Check if this fixes 2.4.1

**Comment by jamalv** [comment]
@maxvisser @GerbenBosschieter why on hold?
