### ISSUE TITLE
Fund request clarification mail: text adjustments

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1789]
## Context/goal: 
<details>
<summary> Fund request clarification mail </summary>

E-mail subject/H1: Uw aanvraag voor :fund_name aanvullen

{{ clarification_message }}

{{ BUTTON: "Ga naar uw aanvraag" }}

![image](https://user-images.githubusercontent.com/10818702/94416678-6ca29200-017f-11eb-8bab-ee62bc06cb53.png)
</details>

## Goal

Goal is to let validator write as much of the e-mail himself. 

## Task
- [ ] change H1/email subject to "Uw aanvraag voor :fund_name aanvullen"
- [ ] remove content of mail: no greeting/salution needed, mail will only contain the message from validator.
- [ ] Change url to a button which contains the text 'Ga naar uw aanvraag'
