### ISSUE TITLE
Fund request created mail: change text

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1791]
## Context/goal: 

![image](https://user-images.githubusercontent.com/10818702/94421681-33b9eb80-0186-11eb-869a-79be0e1ab9da.png)

H1/subject: Uw :fund_name aanvraag is ontvangen

Beste inwoner,

{{:sponsor_org_name note: convert string to start with Capital}} heeft uw :fund_name aanvraag ontvangen. Uw aanvraag is in behandeling. U ontvangt binnen twee weken een reactie op uw aanvraag.

{{ BUTTON: "Ga naar de webshop" URL: webshop implementation }}

## Task

- [ ] change greeting: add comma
- [ ] Add sponsor organization name as variable (should start with capital
- [ ] change body text
- [ ] change text link to button
