### ISSUE TITLE
Implement brand identity of Stadjerpas in requester signupflow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1808]
## Context/goal: 
<details>
<summary>Change stepper to black</summary>

![image](https://user-images.githubusercontent.com/10818702/95050674-47b49e80-06ec-11eb-96cc-c3f6aa6eae67.png)

</details>
<details>
<summary>Text links to red #E60004</summary>

![image](https://user-images.githubusercontent.com/10818702/95050698-4d11e900-06ec-11eb-8394-e2079eb22195.png)

</details>
<details>
<summary>buttons to white on black #191818</summary>

![image](https://user-images.githubusercontent.com/10818702/95050714-5307ca00-06ec-11eb-904f-d9d8115908fc.png)

</details>
<details>
<summary>Next step links to red #E60004</summary>

![image](https://user-images.githubusercontent.com/10818702/95050727-5a2ed800-06ec-11eb-8956-45db3e3fc886.png)

</details>
<details>
<summary>Change SVG's</summary>

![image](https://user-images.githubusercontent.com/10818702/95050833-85192c00-06ec-11eb-8e8c-4e0da4cfd3f1.png)

</details>

<details>
<summary>E-mail sign in input + button</summary>

Example of Nijmegen
![image](https://user-images.githubusercontent.com/10818702/95052086-9a8f5580-06ee-11eb-9cd1-5580fba6aabb.png)

Groningen style will be implemented later

</details>

SVG:
[illustrations.zip](https://github.com/teamforus/forus/files/5325837/illustrations.zip)

https://www.figma.com/file/uIBk2xE4TA2EcqPnU3VvEb/?node-id=176%3A137

## Task
- [ ] change color of stepper
- [ ] Change color of text links
- [ ] DigiD buttons to white with black border
- [ ] Next step links to red
- [ ] Change SVG's for succes and email confirmation
- [ ] Check Font-family used in flow; should be same on rest of site

Note:
Would be nice to change the colors of this flow using CSS variables which can be changed by each implementation.
