### ISSUE TITLE
Webshop: Show products on provider / office details page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1819]
@maxvisser commented on [Mon Oct 05 2020](https://github.com/teamforus/general/issues/485)

Learn more about change requests here: https://bit.ly/39CWeEE

### Requested by:
-

### Change description
Need to be able to see products of that provider on the office and organization details page.
Add a way to go back from products page to office/organization page

## Task
- [ ] Add products block (which is also on voucher) on organization and office page
- [ ] if action fund we should show actions instead.
- [ ] Show a maximum of three products and a button to load more (nine more)
- [ ] Make offices on product page clickable so user can return to office page.
