### ISSUE TITLE
Webshop: Sort products by price (high low, low high)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1850]
## Context/goal: 
https://www.figma.com/file/ehttVgO6MKVZD9feDYMsa7/Sort-by...?node-id=0%3A1&viewport=587%2C1367%2C1.2478587627410889

![image](https://user-images.githubusercontent.com/10818702/96683667-be070100-137a-11eb-8bb4-11a3ea9016fa.png)

## Task
- [ ] Create markup for sorting
- [ ] Implement sorting for price: high to low and low to high, keep sorting by creation date

Dutch text:
Sort -> Sorteer
Price low to high -> Prijs (oplopend)
Price High to low -> Prijs (aflopend)
Newest first -> Nieuwe eerst
Oldest first -> Oudste eerst

## Task
- [ ] Create sorting on price for products

**Comment by maxvisser** [comment]
Prices are currently calculated on the frontend. Sorting can therefor be problematic. (for subsidies). For only products its not that big of a problem.

**Comment by jamalv** [comment]
Easy for regular products, for actions depends on current user and what funds you have. Or could even be free. If you have multiple funds need to find which one is cheaper.

**Comment by jamalv** [comment]
Quickfix; always sort by base price.

On actions we don't show base price.
