### ISSUE TITLE
Improvement of physical cards flow

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1869]
## Task
- [x] change styling of physical cards activating
- [x] change button to open linking physical cards
- [x] move physical cards below voucher card
- [x] removing type selection
- [x] textual changes
	- expire date label
    - modal texts
    - action buttons

**Comment by jamalv** [comment]
Figma needs review @danrminds

**Comment by jamalv** [comment]
@jamalv @danrminds should decide scope

**Comment by maxvisser** [comment]
This is merged already and deployed.
