### ISSUE TITLE
Webshop: Me-app page

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1872]
## Context/goal: 
Implement new Me page webshop: 
https://www.figma.com/file/MKpTh5najQ3Xnq1apodcZa/Webshop-Me-page?node-id=27%3A121

## Task
- [ ] remove all old CSS and images, code
- [ ] add new content from Figma
- [ ] change links to go this new page.
