### ISSUE TITLE
Webshop: provider page 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1918]
## Context/goal: 
https://www.figma.com/file/fpYpPXqKqcQekCpYAI3hqU/Webshop-provider-page?node-id=82%3A1452

## Task
- [ ] Create page with laptop image and texts
- [ ] Footer link needs to be adjusted
- [ ] Button on page should link to "./provider/sign-up"
