### ISSUE TITLE
Time based criteria, prevalidations adjustments

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#1959]
## Context/goal: 

- [ ] Fund configuration for how long a record_type is trusted
	- All record_types from criteria should have the trusted period (if you want to activate voucher directly)
	- Describe all edge cases if trusted period is different:
		- One record is valid, other is not
		- All records are invalid
- [ ] create a prevalidation -> date of creation of prevalidation should added to record/record_validation
- [ ] Requester should be able to get a new voucher when they don’t have an active voucher.
- [ ] Use the expiration date of the voucher itself, ignore the expiration date of the fund.
	- Math.min(fund.expiration_date, voucher.expiration_date);
- [ ] Replace or update ‘creation’/’trusted’ date of a prevalidation
- [ ]  Soft deleting a single prevalidation from table
