### ISSUE TITLE
backend flag CMS toggle: "aanspreekvorm" [je/u]

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2075]
## Description
![image](https://user-images.githubusercontent.com/10818702/105146172-f47e2480-5aff-11eb-905f-414fd07aaf9f.png)

## Text for implementing frontend

**Login met E-mail**
Vul jouw e-mailadres in om een link te ontvangen waarmee je kunt inloggen.

Vergeten welk e-mailadres je hebt gebruikt?

Gebruik de Me-app om makkelijk in te loggen, betalingen te doen en tegoeden te beheren.

**Log in op de website**
Je hebt zojuist een link aangevraagd om in te loggen op de website. Klik hier of op de knop hieronder om in te loggen.
Deze link is geldig tot [date-time].

Inloggen

## Tasks

- [ ] Backend flag (hello world)
- [ ] in cms have toggle: "aanspreekvorm" [je/u]
- [ ] indexing all the places where it's used and adjusting in figma
- [ ] implementing it in the frontend and backend:
  - [ ] login mail
  - [ ] login modal

**Comment by SjoerdHilhorst** [comment]
I see this is closed, whats the status? are all texts updated?

**Comment by maartenfv** [comment]
@maxvisser could you give an update on why this is closed?
