### ISSUE TITLE
As a user I would like to be able to fit my entire logo in the image cropper, without editing the image outside of Forus

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2133]
@jamalv commented on [Wed Apr 29 2020](https://github.com/teamforus/general/issues/177)

## default zoom sate
When uploading an image, we default to zoomed in a bit, but the chance is quite big that I want to show as much as possible of the image. Therefore it would make more sense, in my opinion, to default the cropper to be zoomed out.

Current default
<img width="464" alt="Screenshot 2020-04-29 at 21 34 54" src="https://user-images.githubusercontent.com/30194799/80638894-76558b80-8a61-11ea-92fa-e1f8a35af32d.png">

Requested default
<img width="490" alt="Screenshot 2020-04-29 at 21 36 47" src="https://user-images.githubusercontent.com/30194799/80638928-88cfc500-8a61-11ea-90e6-8d8a128ba9f2.png">

## Allow to zoom out more
Should allow white space.
Should allow black space.
Nice to have: Optional colour picker.

## Dimensions

Check how we show images on webshop; If we tell user to upload a square image; we cant make the cropper rectangle.
- Make sure the cropper is actually square if needed.

![image](https://user-images.githubusercontent.com/30211022/107948510-35007f00-6f94-11eb-8889-c4b640fb0e7b.png)

## Task
- [x] fix Default zoom state
- [x] Check plugin documentation: Allow to zoom out more
- [x] fix dimensions of cropper organization logo square: check where we show the image; if correct adjust texts.

**Comment by jamalv** [comment]
@aghimpu please give a status update

**Comment by maxvisser** [comment]
trying to finish it today
