### ISSUE TITLE
Exporting Physical cards automatically

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#2138]
## Tasks
- [ ] have a database column which tells if physical card request is uploaded to ftp
- [ ] bundle physical card requests on voucher_id with each export so users who accidently requested two cards receive only one.
- [ ] check if voucher of physical card request already has an physical card attached, if so don't export it into the CSV.
- [ ] export only requests which did were not exported before. Migrate all previous requests to already be exported
- [ ] being able to set a specific subfolder in ftp to upload CSV
- [ ] each thursday / friday midnight run a cron job to upload CSV to ftp server

**Comment by maxvisser** [comment]
they now have an API so this issue can be archived
