### ISSUE TITLE
Sponsor dashboard: Add the option to the filter see if BSN and/or e-mail has multiple voucher  (product voucher and voucher page)

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#2359]
## Context/goal: 
In some cases the sponsor creates an extra voucher for a requester, whatever the reason/scenario may be (see image  1 below). The sponsor would like to have an option added to the filter to filter all requesters that have multiple (2 or more) vouchers. This option should filter all BSN and e-mailadressen that have multiple vouchers.

**Task**
- [ ] Add the above to the filter as the example in image 2
- [ ] Filter should work for product vouchers and budget vouchers.
- [ ] Needs text reviews @linda-90 

**Image 1**
<img width="1011" alt="Screenshot 2021-09-10 at 10 34 57" src="https://user-images.githubusercontent.com/38419514/132825827-9dc8b82a-73c3-41ae-9a20-2e34dea306ae.png">

**Image 2**
<img width="1002" alt="Screenshot 2021-09-10 at 10 26 28" src="https://user-images.githubusercontent.com/38419514/132825982-c2be48cf-4cca-455f-8047-183563dcffe0.png">

## Task

Add a dropdown filter to only show accounts with more then >1 voucher

Title: Aantal tegoeden (amount of vouchers)

Dropdown filter has two options:
- n.v.t. (default: show all vouchers)
- meer dan 1 ( More than >1 vouchers)

We could add later values like exactly =1 voucher , exactly =2 vouchers or > 3

**Comment by maxvisser** [comment]
Linda's advice is to not do a bolean field but add a filter based on how many there are
so:
Aantal tegoeden (amount of vouchers)
n.v.t. 
1 of meer ( 1 or more vouchers)
1 (exactly one voucher)
2 (exactly two vouchers)
3 of meer (3 or more vouchers)

**Comment by maxvisser** [comment]
Two inputs
0..2

idea is a bit the same as price ranges (set lowest price and highest price and show product within this price range)
