### ISSUE TITLE
Confirm e-mail via mailbox

### ISSUE THREAD

**Issue by danrminds** [teamforus/forus#280]
# Epic: Confirm e-mail via mailbox

- [x] Confirm mail: seperate creating identity and activating voucher #519
- [x] Confirm mail: Signup via Me teamforus/me#195
- [x] Confirm mail: Signupflow  #520
- [x] Confirm mail: Limit what a non activated user can do. #522 
- [x] Confirm mail: sign up via Me userflow #540

**Comment by maxvisser** [comment]
@danrminds, I think this gets more important also for providers

**Comment by maxvisser** [comment]
# email content
U krijgt deze e-mail omdat u op {{ platform }} uw email adres hebt ingevuld. Met deze e-mail willen we verifieren of u toegang heeft tot dit e-mail adres.

Als u op deze link klikt of op de onderstaande knop wordt uw e-mailadres geverifieerd. 

[button: Verifieer]

**Comment by maxvisser** [comment]
We should start this week by adding this to the api and next week implement it in frontend webshop

**Comment by pantyukhov** [comment]
Done
/nl/sender/user/email_activation
