### ISSUE TITLE
Epic: make mobile design

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#433]
## Context/goal: 
Make mobile version of webshop

- [x] block provider map frontpage #561
- [x] buttons in menu, menu links #563
- [x] login with deeplinking me app instead of qr code. #564
- [x] my vouchers page. #565
- [x] vouchers details. #566

**Comment by maxvisser** [comment]
@danrminds can you add this to a milestone and maybe check if I got everything. Maybe also do some disabled parts like the funds page?

**Comment by maxvisser** [comment]
Mobile menu need some work.. for example: ![image](https://user-images.githubusercontent.com/10818702/50072847-ee0d7800-01d6-11e9-975b-c9a10550dd7a.png)

**Comment by maxvisser** [comment]
Menu is gone here ![image](https://user-images.githubusercontent.com/10818702/50072893-17c69f00-01d7-11e9-9a56-6292e82b6f98.png)
