### ISSUE TITLE
Epic: Funds list, details webshop enhancement

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#665]
## Funds list: 

Frontend: nijmegen.panel, zuidhorn.panel, general.panel
Page: /funds

screenshot of page:
![image](https://user-images.githubusercontent.com/10818702/50789109-989b2700-12bb-11e9-920c-e533df054579.png)

- [x] if only one fund available go directly to fund details page (funds/1 for example) @dev-rminds 
- [x] only list funds you can apply to, if already applied; hide fund @dev-rminds #798 
- [x] Fund page: empty page message #799 
- [x] Show criteria from fund_criteria table (no primary key) @dev-rminds #800 
- [x] remove categories @GerbenBosschieter #802
- [x] remove button, change card to highlight hover and make the whole card clickable. (like products modals on /products page) @dev-rminds #803
- [x] change title \<h1> to 'Aanmelden voor regeling' @GerbenBosschieter #804
- [x] add end date, label NL: 'U kunt uw voucher activeren tot:' @dev-rminds #805
- [x] add breadcrumbs 'Home > Voucher activeren' @GerbenBosschieter #806

## Fund detail:

Frontend: nijmegen.panel, zuidhorn.panel, general.panel
page: funds/1

![image](https://user-images.githubusercontent.com/10818702/50795767-993db880-12cf-11e9-92c6-7cc190584787.png)

- [x] add breadcrumbs @GerbenBosschieter #807
- [ ] add page title <title> {{fund_name}} activeren <\/title> @GerbenBosschieter #808
- [x] show criteria from fund_criteria under criteria @dev-rminds @ateamcms #809 
- [x] change title to NL: '{{fund_name}} aanmelden @GerbenBosschieter #810
- [ ] remove add record when config 'add record' is set to false @dev-rminds #811
- [x] change 'eigenschap waarde' to: 'Eigenschap ontbreekt in uw profiel' @GerbenBosschieter #812
- [x] change apply button text from 'mee doen' to 'Aanmelden' @GerbenBosschieter #813
- [x] show fund details #814
  - [x] show fund end date
  - [x] show sponsor e-mail and telephonenumber
  - [x] show amount formula https://github.com/teamforus/forus/issues/815
   - fixed label NL: Vast bedrag: https://github.com/teamforus/forus/issues/815
   - multiply label NL: Vermenigvuldigd bedrag: https://github.com/teamforus/forus/issues/815
     - record_type_key label NL: Vermenigvuldiger: https://github.com/teamforus/forus/issues/815

## Userflow

- [x] If more than 1 fund, apply automatically to the fund of the activation code. @dev-rminds #797
- [x] and be redirected to his voucher @dev-rminds #797
