### ISSUE TITLE
Epic: My records page enhancement

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#667]
## Context/goal: 

frontend: nijmegen.panel, zuidhorn.panel, general.panel
page: /records
example url: https://dev.nijmegen.forus.io/#!/records

screenshot:
![image](https://user-images.githubusercontent.com/10818702/50796656-92fd0b80-12d2-11e9-9c02-70a4a98ba500.png)

- [x] hide personal QR-code based on backend config webshop.php; Records => validate (hide if false)
- [x] add breadcrumbs
- [x] add button to enter activation code
- [x] change title to 'Eigenschappen' remove 'Mijn'
- [x] if records list is true in backend config. enable right side menu on 'Mijn vouchers' page: /vouchers

![image](https://user-images.githubusercontent.com/10818702/50797009-af4d7800-12d3-11e9-880a-0956c3529f7d.png)

- [x] if records list is true in backend config change 'MIJN VOUCHERS' in top nav to 'OPEN PROFIEL' 
example: 

![image](https://user-images.githubusercontent.com/10818702/50796934-76150800-12d3-11e9-898f-2d2ad015016e.png)

- [x] remove 'Mijn eigenschappen' from top-nav submenu

![image](https://user-images.githubusercontent.com/10818702/50796993-a492e300-12d3-11e9-8338-77f5a2e64cd6.png)

- [ ] show organisation name of identity, instead of identity address of validator, on record validation details
example url: http://localhost:5510/#!/records/7/validations

![image](https://user-images.githubusercontent.com/10818702/54109897-37d5bb00-43e0-11e9-9c38-60ac7e786c48.png)

**Comment by jamalv** [comment]
You want to do this so people can see their personal information?

**Comment by maxvisser** [comment]
Yes and have page where they can edit e-mail adres or other profile settings.
also I see this as the first step of enabling the application proces. maybe even validating BSN with a digid connection.
