### ISSUE TITLE
Epic: Application procedure

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#793]
## Context

This epic is about creating a generic application procedure for applying to funds. 

Currently we use activation codes to generate prevalidation records and these activation codes will be used by citisens to add records to their identity. A record we currently use is kindpakket eligable. This is not a record.

## Proposal

<details><summary>Click to view</summary>

### Abstract
A fund requires an applicant to provide proofs that they meet the criteria of a specific **statement**. A statement can be: I am older then 18 years. Or, I live in municipality X.

A proof is a business rule on a specific records

Example:
Your income needs to be between x and x
A set of proofs are 'Personas' 

![image](https://user-images.githubusercontent.com/10818702/61614763-d1518b00-ac64-11e9-8b5e-fd9c96bf01ab.png)
A persona is a fictional character which a sponsor can relate to; Its a 'preset' of business rules.

A **proof** is a statement supported by a (set of) record(s). 
Proofs will always result in a Bolean: true or false.

A persona is a preset group of proofs that a sponsor can use to identify the target audience.
Proofs are part of your identity
Persona's are part of the platform.
Multiple persona's can be added as a criteria for a fund.

### Current user flow
1. Validator uploads a CSV file to their dashboard
2. Pre-validation tokens are generated with a pre-validation record
3. Tokens are printed out and sent via postal to the requester
4. Requester uses token on the webshop to add the pre-validation records to their identity
5. Currently the requester applies for the fund that the pre-validation records were generated from. These records are fundname_eligible, children_nth and a BSN number.

### Happy flow
1. Sponsor selects a preset of proofs (persona).
2. This preset of proofs will be used to generate a form that a requester can fill in.
3. [user finds the form either trough the webshop or directly on the fund page]
4. User fills in this form, records are created and validation requests are sent to the validator(s) dashboard(s).
5. Validator can ask for additional documents (PDF's / img etc.) to support their validation
6. Requester is notified that their records are validated (data is validated, you can go to the website to complete your application)
7. Requester completes application by sharing the proofs.
</details>

## Issues: 
- [x] Applying: MVP: https://github.com/teamforus/forus/issues/995
- [x] Applying: sponsor policy builder: https://github.com/teamforus/forus/issues/993
- [ ] Applying: sponsor fund configuration [todo]
- [ ] Applying: requester flow [todo]
- [ ] Applying: refine validator flow [todo]

<details><summary>Show wireframes of changes</summary>

## Sponsor changes: 
<details><summary>Show changes</summary>

### ---- Add tab "policy" (in dutch: "beleid")
![forus-platform-sponsor copy](https://user-images.githubusercontent.com/30194799/63426817-055ece00-c414-11e9-9134-947c19ffc390.png)

### ---- Content of policy tab:
![beleid](https://user-images.githubusercontent.com/30194799/63426946-4c4cc380-c414-11e9-8d51-1eaf0316bb38.png)

### ---- Viewing a policy:
![beleid   expanded](https://user-images.githubusercontent.com/30194799/63427047-81591600-c414-11e9-8833-f689c30ee19d.png)

### ----  Editing a policy:
![beleid   edit](https://user-images.githubusercontent.com/30194799/63427155-c715de80-c414-11e9-8440-bdfbc6fb861c.png)

### ---- Creating a fund:
![fonds aanpassen copy](https://user-images.githubusercontent.com/30194799/63427483-7f438700-c415-11e9-8c96-507b7c5fb714.png)

### ---- Add a policy to a fund (modal):
![add policy](https://user-images.githubusercontent.com/30194799/63427560-b0bc5280-c415-11e9-9a5c-a79abadc49ae.png)

</details>

## Requester changes: 
<details><summary>Show changes</summary>

### ---- Show requirements (+status if logged in) + application button
![apply](https://user-images.githubusercontent.com/30194799/63427711-1577ad00-c416-11e9-8487-e487cddc9b32.png)

### ---- Fill requirements (in form) to be validated
![application form](https://user-images.githubusercontent.com/30194799/63427985-b8302b80-c416-11e9-9e55-a30b9deb164e.png)

### ---- Show confirmation
![confirmation message](https://user-images.githubusercontent.com/30194799/63428032-d7c75400-c416-11e9-9102-72ae47263a76.png)

</details>

## Validator changes: 
<details><summary>Show changes</summary>

### ---- Validator dashboard concept
![validator-concept](https://user-images.githubusercontent.com/30194799/63428350-a733ea00-c417-11e9-8a2d-890a930b9f03.png)

</details>
</details>
</details>

**Comment by jamalv** [comment]
updated the description

**Comment by maartenfv** [comment]
@jamalv Tijdens het afgelopen overleg is aangegeven dat het vermogen ook mee moet worden genomen in de check.

**Comment by maxvisser** [comment]
@jamalv do you want to close this one in favor of development issue?
