### ISSUE TITLE
Make figma proposal: give the organisation the option to enable citizens to apply for fund (fund settings)

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#795]
## Context/goal: 

signupflow should be a fund config, this way we can start using the flow with one fund and one municipality and scale up when it works

## Task
- [x] text for page is blocked
- [x] message where to request fund (if there is?)
- [x] text for page when you already requested fund
- [ ] add a option in edit fund that enables applications (or disable)
- [ ] https://westerkwartier.forus.io/fund/8/request
- [ ] Make it so that user can still activate vouchers using DigiD.

**Comment by maxvisser** [comment]
currently all applications can be done via a form;

**Comment by jamalv** [comment]
can be implemented with frontend flag

**Comment by jamalv** [comment]
should still be able to activate but not apply

**Comment by maxvisser** [comment]
All cases I see which has influance:

Case 1: A requester has a fund request which is approved 
We should show no error but redirect to voucher

Case 2: A requester has a fund request which is denied

Case 3: A requester has a fund request which is partly approved, partly denied

Case 4: A requester has a fund request which is pending

Case 5: A requester has no fund request and fund requesting is done via activationcodes and fund requesting via form is disabled

Case 6: A requester has no fund request and fund requesting is done via DigiD and fund requesting via form is disabled

**Comment by maxvisser** [comment]
@danrminds Could we discuss this one ?
