### ISSUE TITLE
Epic: Product filters

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#840]
- [ ] filter based on location https://github.com/teamforus/forus/issues/576
- [ ] filter based on amount/price
- [ ] filter based on provider organisation
- [ ] filter based on profile settings

**Comment by maxvisser** [comment]
![Shopping items (Radioboxes)](https://user-images.githubusercontent.com/10818702/55546531-d697c380-56cf-11e9-91a7-d6fce85a909a.png)
