### ISSUE TITLE
Epic: Signup-flow: Provider

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#867]
## Context/goal: 

- [x] checking IBAN is companies IBAN https://github.com/teamforus/forus/issues/778

- [x] Sign-up flow: moving step 5 and 6 before creating organisation https://github.com/teamforus/forus/issues/824

- [x] Sign-up flow: adding creating identity with phonenumber https://github.com/teamforus/forus/issues/825

<details><summary>Step 1: Download</summary>

![step1-download](https://user-images.githubusercontent.com/30194799/57479796-8e575c80-729e-11e9-969b-0579a1fc7ec2.png)
</details>

<details><summary>Step 2: Login</summary>

![step2-login](https://user-images.githubusercontent.com/30194799/57479826-9fa06900-729e-11e9-9602-8ff943ebe549.png)
</details>

<details><summary>Step 3: Add organisation</summary>

![step3-add-organisation](https://user-images.githubusercontent.com/30194799/57479874-bd6dce00-729e-11e9-8d1e-45b718ac9660.png)
</details>

<details><summary>Step 4: Add office</summary>

![step4-add-office](https://user-images.githubusercontent.com/30194799/57479909-cc548080-729e-11e9-96ad-6595869bb1ef.png)
</details>

<details><summary>Step 5: Add employees</summary>

![step5-add-employees](https://user-images.githubusercontent.com/30194799/57479977-deceba00-729e-11e9-90fb-15731d6a492d.png)
</details>

<details><summary>Step 6: Apply for fund</summary>

![step6-apply-to-fund](https://user-images.githubusercontent.com/30194799/57479997-ee4e0300-729e-11e9-9836-7670070d51d0.png)
</details>

And finish with a succes message 😄 

[view all wireframes in draw.io](https://www.draw.io/?state={"folderId":"1XQN2q1xfcHTbnajKoaVA6IdrkwsZGFU0","action":"create","userId":"106232674492770103068"}#G18nwIr0OfMXQvIWj6QiBUnldKRqQXwNM2)

**Comment by jamalv** [comment]
# Steps:
## Downloaden
## Gebruik me
## Inloggen met me
## Organisatie aanmaken
## Vestiging toevoegen
## Medewerkers toevoegen
## Aanmelden regeling

**Comment by jamalv** [comment]
refined issue

**Comment by maxvisser** [comment]
I think issue is the only one left for this flow: https://github.com/teamforus/forus/issues/868
