### ISSUE TITLE
Epic: Product meedoen-regeling

### ISSUE THREAD

**Issue by jamalv** [teamforus/forus#903]
**Context:** deze pagina is bedoeld om de meedoen regeling aan gemeente aan te bieden (uiteraard uitgegeven via ons platform). We kunnen hier de hele regeling presenteren en wat er voor nodig is om deze te implementeren. Dit sluit aan op waar @maartenfv en @linda-90 mee bezig zijn, ondersteuning bij implementatie op afstand. Eerste focus is om de regeling en de voordelen ervan goed en helder te presenteren, het volgende onderdeel van de funnel is implementatie ondersteuning.

- [ ] duidelijke uitleg over de regeling
- [ ] voordelen voor inwoner
- [ ] politieke context etc
- [ ] voorbeeld brieven
- [ ] college advies
- [ ] uit welke budgetten?

**Comment by jamalv** [comment]
@maartenfv De teksten staan in de wireframes, https://www.forus.io/kindpakket is als leidraad te gebruiken. Hoe meer we deze pagina’s kunnen standaardiseren, hoe beter. Dus als we veranderingen willen doorvoeren is het het beste om dat dan ook voor alle product pagina’s te doen.
