### ISSUE TITLE
use google business types and product categories 

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#917]
## Context/goal: 
As discussed in refinement our current approach of sponsor decides categories (create them) is not scalable

product category list
https://www.google.com/basepages/producttype/taxonomy-with-ids.nl-NL.txt

## Tasks
- [ ] first undo all restrictions based on categories (fund list on provider dashboard /  signupflow)
- [ ] add product category list of google https://www.google.com/basepages/producttype/taxonomy-with-ids.nl-NL.txt
- [ ] add business category list of google https://www.reputatiecoaching.nl/nieuwe-categorieen-voor-zakelijke-google-paginas/
- [ ] Make picker work with thousands of categories #912 
- [ ] service providers (service product categories) https://github.com/teamforus/forus/issues/917#issuecomment-522263082
- [ ] Make sure charity or ¨Goed doel¨ is a category for project-30

**Comment by maxvisser** [comment]
Category list for services:

Huis en Tuin
    Aannemers
    Dakdekkers en Rietdekkers
    Elektriciens
    Gevelrenovatie en Voegers
    Glaszetters
    Klussers en Klusbedrijven
    Lassers en Metaalbewerking
    Loodgieters en Installateurs
    Schilders en Behangers
    Slopers
    Stukadoors en Tegelzetters
    Timmerlieden en Meubelmakers
    Tuinmannen en Stratenmakers
    Gereedschap en Machines
    Vloerleggers en Parketteurs
    Zonweringinstallateurs
    Alarm en Beveiliging
    Interieuradviseurs
    Schoorsteenvegers
Kleine reparaties
    Antiek, Klokken en Meubels
    Edelsmeden en Sieradenmakers
    Kleding en Schoenen
    Audio, Tv en Foto
    Muziekinstrumenten
    Pc's en Spelcomputers
    Telecommunicatie
    Witgoed en Apparatuur
Auto en Vervoer
    Monteurs en Garages
    Caravans en Campers
    Fietsenmakers en Bromfietsenmakers
    Poetsers en Wassers
    Schadeherstellers en Spuiterijen
    Watersport en Boten
    Chauffeurs en Taxi's
    Verhuizers en Opslag
    Auto en Motor
    Rijscholen
Huishouden, Gezin en Dier
    Huishoudelijke hulp
    Ongediertebestrijding
    Oppas en Kinderopvang
    Thuiszorg en Kraamhulp
    Wasserettes en Stomerijen
    Honden Hulp
    Katten Hulp
    Paarden Hulp
Recreatie
    Kinderfeestjes
    Groepsuitjes
    Restaurants
    Zwemmen
    Theater, bioscoop en concerten
Zakelijke diensten
    Schoonmakers en Glazenwassers
    Boekhouders
    Geld en Leningen
    Hypotheken en Verzekeringen
    Juristen en Notarissen
    Makelaars en Taxateurs
    Zakelijk adviseurs
    Bouwkundigen en Architecten
    Computer en Internet
    Drukwerk en Grafisch ontwerpers
    Film- en Videobewerking
    Fotografen
    Promotie- en Reclamebureaus
    Vertalers, Tolken en Tekstschrijvers
    Webdesigners en Hosting
    Detectivebureaus
Cursus, Workshop en Les 
    Kunst en schilderen
    Muziekles en Zangles
    Bijles en Taalles
    Coaching
    Cursussen en Workshops
Sport en Welzijn,
    Personal Trainer
    Zwemonderwijzing, 
    Aerobics
    Voedingsdeskundige, Diëtist
    Therapeuten
    Mindfulness
    Stoppen met roken
    Yoga
Uiterlijk en Verzorging
    Alternatieve geneeskunde
    Masseurs en Massagesalons
    Uitvaartverzorging
    Kappers en Thuiskappers
    Kledingadvies en Stylisten
    Kleermakers en Kledingontwerpers
    Manicure
    Pedicure
    Schoonheidsspecialisten
Goede doelen
    Dieren
    Gezondheid
    Internationale hulp en mensenrechten
    Kunst en cultuur
    Natuur en mileu
    Onderwijs
    Religie en levensbeschouwing
    Sport en Welzijn

**Comment by maxvisser** [comment]
- 0: {id: 1, key: "boeken", service: 0, name: "Boeken"}
  -  784 - Media > Boeken
- 1: {id: 2, key: "fiets", service: 0, name: "Fiets"}
  - 1026 - Sportartikelen > Buitenrecreatie > Fietsen (sport) > Fietsen
- 2: {id: 3, key: "sport-accessoires", service: 0, name: "Sport accesoires"}
  - 988 - Sportartikelen
- 3: {id: 4, key: "zwemmen", service: 0, name: "Zwemmen"}
  - 1144 - Sportartikelen > Buitenrecreatie > Boten en watersport > Zwemmen
- 4: {id: 5, key: "computer", service: 0, name: "Computer"}
  - 222 - Elektronica
5: {id: 6, key: "kleding", service: 0, name: "Kleding"}
  - 166 - Kleding en accessoires
6: {id: 7, key: "speelgoed", service: 0, name: "Speelgoed"}
  - 1239 - Speelgoed en spellen

**Comment by maxvisser** [comment]
- 0: {id: 8, key: "cultuur", service: 1, name: "Cultuur"}
  - Recreatie, culturele activiteiten
- 1: {id: 9, key: "cursussen", service: 1, name: "Cursussen"}
  - Cursus, Workshop en Les
- 2: {id: 10, key: "spiritueel", service: 1, name: "Spiritueel"}
  - Sport en Welzijn
- 3: {id: 11, key: "sport", service: 1, name: "Sport en fitness"}
  - Sport en Welzijn
- 4: {id: 12, key: "recreatie", service: 1, name: "Recreatie"}
  - Recreatie, culturele activiteiten
