### ISSUE TITLE
Fund list on provider dashboard: show only funds of implementation

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#961]
## Context/goal: 
On fund list (which a provider can apply to) we currently show all funds a provider is applicable for (based on categories)

## Tasks
- [ ] only showing funds of client_key
- [ ] provider should always be able to apply even if he has the wrong categories
- [ ] on general dashboard we should all funds.
