### ISSUE TITLE
Use Awesome-qr to show Me-logo inside QR-code

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#963]
## Context/goal: 
Authentication QR-code should show Me-logo inside QR-code

## Task
- [ ] investigate if https://github.com/SumiMakito/Awesome-qr.js is a good library to do this
- [ ] implement Me logo inside QR-code (@maxvisser has svg of logo)
- [ ] product voucher image
