### ISSUE TITLE
Website Milestone: 26 July.

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/forus#964]
- [x] Summarise feedback (from product focused to customer focused)
- [x] Create wireframes (22 July)
- [x] Feedback moment (26 July)
- [x] Decide scope before design phase
