### ISSUE TITLE
show BUNQ costs on financial dashboard

### ISSUE THREAD

**Issue by maxvisser** [teamforus/forus#991]
## Context/goal: 
We need to calculate BUNQ costs for our clients and show it on the financial dashboard. Municipalitites use their own bunq account for transactions. The use of such an account costs money:
https://www.bunq.com/nl/pricing/business

we currently don't show any information about these costs. This issue is about calculating the costs of bunq and show it on the sponsor dashboard.

## tasks
- [x] a transaction from sponsor to provider costs 10 cents
- [ ] a bunq account has a monthly fee of 10 euro's
- [ ] if an municipalities stores more than 100k, it costs 2,4 cents a day.
- [ ] is there an api to request the latest BUNQ costs or should we configure these costs manually?

**Comment by TomForus** [comment]
In onderstaand overzicht staan alle kosten:

bunq.com/nl/pricing/business
